### ISSUE TITLE
Support for Hub (mini) API instead of direct BLE?

### ISSUE THREAD

**Issue by DJay-X** [OpenWonderLabs/homebridge-switchbot-ble#1]
Hi Guys. I hope you are all doing well.

Happy to see, that you start with Homebridge integration.
However, only direct BLE support can be a challenge.
Using API and Hub (mini) would be an easer alternative for a lot of other users, because using BLE setup and the need to install bluetooth bluez, can cause problems on existing setups.

API with Hub, alt least in addition would be a smart choice. 

Do you plan this integration with reliable Hub connection and a Homebridge Plugin and also of course then support of SwitchBot Curtain?

Thanks again for you the time you are investing, your work and sharing with the community.

**Comment by Kohle81** [comment]
I would also welcome the integration of the hub, since I use it and don't have a Raspberry nearby.  Would be nice!!!

**Comment by DJay-X** [comment]
> I would also welcome the integration of the hub, since I use it and don't have a Raspberry nearby. Would be nice!!!

Good point. Thanks.
@SwitchBot @SwitchBot-Wonderlabs By having a SwitchBot Homebridge Plugin that uses the Hub API instead the BLE, the plugin can then also used in NAS/Docker and iMac etc.
As mentioned using BLE bluez conflicts with the system are more possible.

**Comment by SwitchBot-Wonderlabs** [comment]
We are dealing with RESTful API of Hub.
It is planned to be available at the end of this year.

**Comment by benjaminbogdanovic** [comment]
Will the RESTful API be just an API for developers to use, or will you create a Homebridge plugin that integrates it?

**Comment by SwitchBot-Wonderlabs** [comment]
> Will the RESTful API be just an API for developers to use, or will you create a Homebridge plugin that integrates it?

We will create an api interface module and a homebridge plugin.

**Comment by benjaminbogdanovic** [comment]
Glad to hear that. Thanks! Will the Homebridge plugin also be ready by the end of this year? Will it connect to the Hub via wifi instead of bluetooth?

**Comment by SwitchBot-Wonderlabs** [comment]
> Glad to hear that. Thanks! Will the Homebridge plugin also be ready by the end of this year? Will it connect to the Hub via wifi instead of bluetooth?

Yes. Homebridge sends the commands to the server first, and the server forwards the commands to the Hub.
Hub controls the device using BLE.
We try to provide relevant modules and plugins at the end of the year.

**Comment by benjaminbogdanovic** [comment]
Thanks for the explanation. It is a shame to hear that it will rely on a server, and not work locally without an internet connection. I sure other people will feel the same. The implementation you describe sounds similar to using IFTTT with webhooks and the IFTTT Homebridge plugin.

**Comment by SwitchBot-Wonderlabs** [comment]
> Thanks for the explanation. It is a shame to hear that it will rely on a server, and not work locally without an internet connection. I sure other people will feel the same. The implementation you describe sounds similar to using IFTTT with webhooks and the IFTTT Homebridge plugin.

It is not our main job, but we will gradually open up related functions. 
Thanks for your support.

**Comment by yudai-nkt** [comment]
Happy to see you are working on REST API for Hub, @SwitchBot-Wonderlabs! Does the API include IR control, or just the manipulation of your products (e.g., bot and curtain)? I hope IR control can be done via API as well.

**Comment by SwitchBot-Wonderlabs** [comment]
> Happy to see you are working on REST API for Hub, @SwitchBot-Wonderlabs! Does the API include IR control, or just the manipulation of your products (e.g., bot and curtain)? I hope IR control can be done via API as well.

Will support IR, but there are too many  IR devices types，air conditioner and some switches first.

**Comment by DJay-X** [comment]
> We are dealing with RESTful API of Hub.
> It is planned to be available at the end of this year.

Hi Guys. I hope you are all doing well.
Mid Nov. Any news on Homebridge Plugin using Hub API instead of BLE?
Looking forward to use it with my SwitchBot Curtain.
Thanks in advance.

**Comment by SwitchBot-Wonderlabs** [comment]
> Hi Guys. I hope you are all doing well.
> Mid Nov. Any news on Homebridge Plugin using Hub API instead of BLE?
> Looking forward to use it with my SwitchBot Curtain.
> Thanks in advance.
API interface is being tested.
If there is no problem, we will start developing the plug-in.

**Comment by MikeDeltaHH** [comment]
@SwitchBot-Wonderlabs
Any date for release?

**Comment by hzx1987227** [comment]
I have no Raspberry device or BLE dongle but mini hub.

Please add API support for mini hub, then i can call the API from home assistant

Thank you

**Comment by SDeath667** [comment]
I'd also love an API, can't wait for it to be released. I have a hub mini with a few meters that I'd like to be able to read using the WiFi from the hub mini into my Fibaro HC2 home automation.
I might upgrade other equipment and get more hub mini's and meters for my filament boxes and to monitor humidity in our home.

**Comment by DJay-X** [comment]
Maybe in the not so far future?! 😉

https://github.com/OpenWonderLabs/SwitchBotAPI
https://github.com/donavanbecker/homebridge-switch-bot

**Comment by Kohle81** [comment]
It would be a nice Christmas present

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SDeath667** [comment]
Looking good!
Unable to find the generate token in the app yet so I guess we have to wait for that.
The example links are giving me the Unautorized responses so it seems to be up.

**Comment by SDeath667** [comment]
YES new app version!!!!
Nope nothing API related. Crap!

**Comment by Minsheng** [comment]
Hi guys, this is Davidson from the dev team. The good news is the API is up and running. However, the Generate Token feature will be released in the next app feature update for both platforms. Android release will come first before Christmas but iOS release will likely take another 2 weeks. If you want to test it out right away, kindly make a request from the app using Feedback and we will generate a token for you as a temp solution. You will be able to reset the token in the next app release. How does that sound?

**Comment by SDeath667** [comment]
Thanks Davidson!
Put in the request already. 
Thank you!
Now I can develop a Fibaro HC2 integration.

**Comment by Kohle81** [comment]
This sounds great, I am happy to hear this! Thanks for your work!

**Comment by DJay-X** [comment]
Closing this "Issue" and pointing to https://github.com/OpenWonderLabs/homebridge-switchbot-openapi/issues/9
