### ISSUE TITLE
It’s can be used without SwitchBot Hub?

### ISSUE THREAD

**Issue by Dansteris** [OpenWonderLabs/homebridge-switchbot-ble#11]
Can I use it without buying SwitchBot Hub?

**Comment by FishyD** [comment]
Yes, this uses Bluetooth on the Homebridge device, this is why you first have to install the BLE package. It seems that a new plug-in due out later this year will utilize the Hub Mini's communication with the SwitchBot which is a much better way to go, in my opinion.

**Comment by SwitchBot-Wonderlabs** [comment]
> Can I use it without buying SwitchBot Hub?
Hi, @Dansteris ,
As @FishyD said.
