### ISSUE TITLE
Homebridge on MacOS

### ISSUE THREAD

**Issue by Endlessknight** [OpenWonderLabs/homebridge-switchbot-ble#13]
My Homebridge is running on my MacMini that. Apparently nothing seems to work. Neither the curtains nor the SwitchBot itself.
The plugin does install without any errors, I can add the MAC ID of both devices but there seems to be no communication between any SwitchBot device and the MacMini

**Comment by SwitchBot-Wonderlabs** [comment]
Duplicate of #3
