### ISSUE TITLE
Device state is not checked

### ISSUE THREAD

**Issue by dnicolson** [OpenWonderLabs/homebridge-switchbot-ble#14]
When HomeKit performs a state update, the device is not checked for the state and only relies on the initial default "OFF" state. This results in all devices being "OFF" if Homebridge is restarted.

The `targetState` variable is declared but never used:
https://github.com/SwitchBot/homebridge-switchbot-ble/blob/ec96d90aac9da6e8d200c25045f1bac9f7fbe809/src/bot-accessory.ts#L40

Would a pull request be accepted that checks the device (at least the initial state) by checking the [advertisement](https://github.com/futomi/node-switchbot#monitoring-advertising-packets) data?

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @dnicolson ,
We know this. 
We will use advertising to initialize and periodically update the state.
This update operation is the behavior of the platform, not of each device.
Currently, Meter uses advertising to periodically update temperature and humidity.
Welcome to submit the pull request.

**Comment by dnicolson** [comment]
I'm not sure I understand correctly, is it planned to read advertising data on a platform level?

**Comment by dnicolson** [comment]
@OpenWonderLabs, @SwitchBot-Wonderlabs, can I ask why there is a need to close issues that have not been properly answered?

**Comment by donavanbecker** [comment]
Version 1.5.0 released.
