### ISSUE TITLE
Support for Humidifier

### ISSUE THREAD

**Issue by donavanbecker** [OpenWonderLabs/homebridge-switchbot-ble#20]
Any thoughts on adding SwitchBot Humidifier support?

**Comment by donavanbecker** [comment]
@SwitchBot-Wonderlabs @SwitchBot @dnicolson @whatUwant 

Anyway to add this support? I can provide info.

Also have you considered getting your plugin verified by the homebridge community? 

https://github.com/homebridge/verified

**Comment by whatUwant** [comment]
> @SwitchBot-Wonderlabs @SwitchBot @dnicolson @whatUwant 
> 
> 
> 
> Anyway to add this support? I can provide info.
> 
> 
> 
> Also have you considered getting your plugin verified by the homebridge community? 
> 
> 
> 
> https://github.com/homebridge/verified

I'm not affiliated with SwitchBot.
But yeah I think they should get the plug-in verified.

**Comment by donavanbecker** [comment]
FYI: [SwitchBotAPI](https://github.com/OpenWonderLabs/SwitchBotAPI)
