### ISSUE TITLE
After adding the config lines, crashing homebridge

### ISSUE THREAD

**Issue by rcuijpers** [OpenWonderLabs/homebridge-switchbot-ble#21]
Hi guys!

I'm trying to install your plugin in my homebrigde setup but everytime I add the json to the config file it keeps homebrigde from rebooting.

Dec 06 13:13:50 raspberrypi systemd[1]: Started Homebridge.
†Dec 06 13:13:52 raspberrypi homebridge[3073]: [12/6/2020, 1:13:52 PM] Loaded config.json with 1 accessories and 6 platforms.
Dec 06 13:13:52 raspberrypi homebridge[3073]: [12/6/2020, 1:13:52 PM] ---
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Loaded plugin: homebridge-cmdswitch2@0.2.10
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Registering platform 'homebridge-cmdswitch2.cmdSwitch2'
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] ---
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Loaded plugin: homebridge-config-ui-x@4.35.0
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Registering platform 'homebridge-config-ui-x.config'
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] ---
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Loaded plugin: homebridge-gsh@2.0.1
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Registering platform 'homebridge-gsh.google-smarthome'
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] ---
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Loaded plugin: homebridge-klikaanklikuit@1.2.0
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] Registering platform 'homebridge-klikaanklikuit.KlikAanKlikUit'
Dec 06 13:13:53 raspberrypi homebridge[3073]: [12/6/2020, 1:13:53 PM] ---
Dec 06 13:13:54 raspberrypi homebridge[3073]: [12/6/2020, 1:13:54 PM] Loaded plugin: homebridge-nefit-easy@2.2.0
Dec 06 13:13:54 raspberrypi homebridge[3073]: [12/6/2020, 1:13:54 PM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
Dec 06 13:13:54 raspberrypi homebridge[3073]: [12/6/2020, 1:13:54 PM] ---
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Loaded plugin: homebridge-nest@4.5.1
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Registering platform 'homebridge-nest.Nest'
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] ---
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Loaded plugin: homebridge-wol@4.3.0
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Registering accessory 'homebridge-wol.NetworkDevice'
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] ---
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Loaded plugin: @switchbot/homebridge-switchbot-ble@1.2.3
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Registering platform '@switchbot/homebridge-switchbot-ble.SwitchBotPlatform'
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] ---
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Loading 6 platforms...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [Config] Initializing config platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [Config] Spawning homebridge-config-ui-x with PID 3093
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [SwitchBotPlatform] Initializing SwitchBotPlatform platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [SwitchBotPlatform] SwitchBot platform finished initializing!
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [CMD Switch] Initializing cmdSwitch2 platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [Nest] Initializing Nest platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [Google Smart Home] Initializing google-smarthome platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] using driver 'rpi'
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] initialized RPi driver (pin 8)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'Deurbel Beneden' (address = B, device = 2)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding lightbulb 'Koperlamp' (address = 2637, device = 1)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'ReserveA2' (address = A, device = 2)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'ReserveA3' (address = A, device = 3)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'Kerstboom' (address = A, device = 1)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'Camera Woonkamer' (address = C, device = 2)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [KlikAanKlikUit] [homebridge-klikaanklikuit] adding outlet 'MacBook Lader' (address = C, device = 3)
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'Deurbel Beneden'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'Koperlamp'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'ReserveA2'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'ReserveA3'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'Kerstboom'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'Camera Woonkamer'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Initializing platform accessory 'MacBook Lader'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] Loading 1 accessories...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [NefitEasy] Initializing NefitEasy accessory...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [CMD Switch] Initializing platform accessory 'Playstation 4 Pro'...
Dec 06 13:13:55 raspberrypi homebridge[3073]: [12/6/2020, 1:13:55 PM] [Nest] Fetching Nest devices.
Dec 06 13:13:57 raspberrypi homebridge[3073]: [12/6/2020, 1:13:57 PM] TypeError: this.config.devices is not iterable
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at SwitchBotPlatform.accessories (/usr/lib/node_modules/@switchbot/homebridge-switchbot-ble/src/switchbot-platform.ts:61:36)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at /usr/lib/node_modules/homebridge/src/server.ts:415:24
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at new Promise (<anonymous>)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Server.loadPlatformAccessories (/usr/lib/node_modules/homebridge/src/server.ts:414:12)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at /usr/lib/node_modules/homebridge/src/server.ts:402:28
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Array.forEach (<anonymous>)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Server.loadPlatforms (/usr/lib/node_modules/homebridge/src/server.ts:374:27)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:153:29)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Module._compile (node:internal/modules/cjs/loader:1102:14)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Module.load (node:internal/modules/cjs/loader:967:32)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Function.Module._load (node:internal/modules/cjs/loader:807:14)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
Dec 06 13:13:57 raspberrypi homebridge[3073]:     at node:internal/main/run_main_module:17:47
Dec 06 13:13:57 raspberrypi homebridge[3073]: [12/6/2020, 1:13:57 PM] Got SIGTERM, shutting down Homebridge...
^[[BDec 06 13:13:58 raspberrypi homebridge[3073]: [12/6/2020, 1:13:58 PM] [Google Smart Home] Connected (1) - wss://homebridge-gsh.iot.oz.nu
^[[BDec 06 13:14:02 raspberrypi homebridge[3073]: [12/6/2020, 1:14:02 PM] [Nest] initing home_away_sensor "Home Occupied": deviceId: axxxx-73bd-11e8-852d-1xxxx640 structureId: ae2602e0-73bd-11e8-xxxx-128a9xxx640
Dec 06 13:14:02 raspberrypi homebridge[3073]: [12/6/2020, 1:14:02 PM] [Nest] initing protect "Entryway": deviceId: 18B4xxxx00AxxxA0BF structureId: ae2602e0-73bd-11e8-852d-xxxxx640
Dec 06 13:14:02 raspberrypi homebridge[3073]: [12/6/2020, 1:14:02 PM] [Nest] initing protect "Portaal": deviceId: 1xxxx1C4A7 structureId: aexxx02e0-73bd-11e8-852d-128a9xxxxx0
Dec 06 13:14:02 raspberrypi homebridge[3073]: [12/6/2020, 1:14:02 PM] [Nest] initing protect "Living Room": deviceId: 18B430xxxA19F03 structureId: ae2602e0-73bd-1xxxe8-852d-128xxxxx40
Dec 06 13:14:03 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Dec 06 13:14:03 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.
Dec 06 13:14:03 raspberrypi homebridge[3073]: [12/6/2020, 1:14:03 PM] [Homebridge UI] Homebridge Config UI X v4.35.0 is listening on :: port 8080
Dec 06 13:14:06 raspberrypi systemd[1]: homebridge.service: Service RestartSec=3s expired, scheduling restart.
Dec 06 13:14:06 raspberrypi systemd[1]: homebridge.service: Scheduled restart job, restart counter is at 4.
Dec 06 13:14:06 raspberrypi systemd[1]: Stopped Homebridge.

I don't really understand whats going wrong. 
Maybe you guys can help me figure it out? :)

Thanks a million!

**Comment by SwitchBot-Wonderlabs** [comment]
Please post your config.

**Comment by rcuijpers** [comment]
Okay, not crashing anymore but homebridge doesnt pick up any data.

`{
    "bridge": {
        "name": "Homebridge",
        "username": "CB:22:3D:E2:CE:31",
        "port": 51826,
        "pin": "033-44-254"
    },
    "accessories": [
        {
            "accessory": "NefitEasy",
            "name": "NefitEasy",
            "options": {
                "serialNumber": "XXXXXX",
                "accessKey": "XXXXXX",
                "password": "XXXXX"
            }
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8080,
            "auth": "form",
            "theme": "dark-mode",
            "restart": "sudo -n systemctl restart homebridge",
            "tempUnits": "c",
            "sudo": true,
            "log": {
                "method": "systemd"
            },
            "platform": "config"
        },
        {
            "platform": "cmdSwitch2",
            "name": "CMD Switch",
            "switches": [
                {
                    "name": "Playstation 4 Pro",
                    "on_cmd": "ps4-waker -d 192.168.1.141 ",
                    "off_cmd": "ps4-waker -d 192.168.1.141  standby",
                    "state_cmd": "ps4-waker -d 192.168.1.141  search | grep -i '200 Ok'",
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000,
                    "manufacturer": "Sony Corporation",
                    "model": "CUH-7116B",
                    "serial": "XXXXXXXXXX"
                }
            ]
        },
        {
            "platform": "Nest",
            "googleAuth": {
                "issueToken": "XXXXXXX",
                "cookies": "XXXXXXXXX",
                "apiKey": "XXXXXXXXX"
            }
        },
        {
            "name": "Google Smart Home",
            "token": "XXXX.XXXXX.XXXXXXX",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
        },
        {
            "platform": "KlikAanKlikUit",
            "driver": {
                "type": "rpi",
                "pin": 8
            },
            "accessories": [
                {
                    "name": "Deurbel Beneden",
                    "type": "Outlet",
                    "address": "B",
                    "device": "2"
                },
                {
                    "name": "Koperlamp",
                    "type": "Lightbulb",
                    "dimmable": true,
                    "address": 2637,
                    "device": 1
                },
                {
                    "name": "ReserveA2",
                    "type": "Outlet",
                    "address": "A",
                    "device": "2"
                },
                {
                    "name": "ReserveA3",
                    "type": "Outlet",
                    "address": "A",
                    "device": "3"
                },
                {
                    "name": "Kerstboom",
                    "type": "Outlet",
                    "address": "A",
                    "device": "1"
                },
                {
                    "name": "Camera Woonkamer",
                    "type": "Outlet",
                    "address": "C",
                    "device": "2"
                },
                {
                    "name": "MacBook Lader",
                    "type": "Outlet",
                    "address": "C",
                    "device": "3"
                }
            ]
        },
        {
            "devices": [
                {
                    "type": "meter",
                    "name": "Gamekamer Thermostaat",
                    "bleMac": "C2:19:CB:A8:7A:E4",
                    "scanDuration": 5000,
                    "scanInterval": 60000
                }
            ],
            "name": "SwitchBotPlatform",
            "platform": "SwitchBotPlatform"
        }
    ]
}`

**Comment by rcuijpers** [comment]
Do you need to set the meter to pairing mode or should the raspberry pick it up without the sensor being in pairing mode?

**Comment by SwitchBot-Wonderlabs** [comment]
Hey @rcuijpers , check HomeBridge version and upgrade the plug-in to v1.2.7

**Comment by rcuijpers** [comment]
Everything is updated.
![Uploading 46F9AB71-F024-48FA-A7DC-9F06ED62A758.jpeg…]()
