### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by hzx1987227** [OpenWonderLabs/homebridge-switchbot-ble#25]
Hi,

How can i get the pos , lightlevel, bettery info from switchbot curtain ?

Currently i can only send open , close , pause command via ESP32.

Thank you.

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @hzx1987227 ,
see [here](https://github.com/futomi/node-switchbot/blob/master/README.md).
`
{
  "id": "ec58c5d00111",
  "address": "ec:58:c5:d0:01:11",
  "rssi": -39,
  "serviceData": {
    "model": "c",
    "modelName": "WoCurtain",
    "calibration": true,
    "battery": 91,
    "position": 1,
    "lightLevel": 1
  }
}
`
