### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by runecatz** [OpenWonderLabs/homebridge-switchbot-ble#3]
Having the following issue where it says device is not found, the BLE Mac is correct:

[11/2/2020, 19:34:25] [SwitchBotPlatform] Scan done.
[11/2/2020, 19:34:25] [SwitchBotPlatform] WoCurtain 
[11/2/2020, 19:34:25] [SwitchBotPlatform] WoCurtain 
[11/2/2020, 19:34:25] [SwitchBotPlatform] WoCurtain 
[11/2/2020, 19:34:25] [SwitchBotPlatform] No device was found.
[11/2/2020, 19:34:25] [SwitchBotPlatform] Error: No device was found.
    at /usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/src/curtain-accessory.ts:77:24
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/@switchbot/homebridge-switchbot-ble/src/curtain-accessory.ts:76:22
[11/2/2020, 19:34:25] [SwitchBotPlatform] Target position of the Curtain setting failed!

**Comment by SwitchBot-Wonderlabs** [comment]
Oh, this is a wrong prompt.
It means that the mac address configured in CONFIG FILE was not found.
You can try to increase the scan time.

**Comment by runecatz** [comment]
I have set it to 4000 and still same issue, what should I set the scan time too?

**Comment by SwitchBot-Wonderlabs** [comment]
If the mac address you set in the config file is not printed, check the distance between the curtain and the homebridge device, and increase the scan time.

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @runecatz , any updates?

**Comment by runecatz** [comment]
I’ve put it right next to the SwitchBot curtain and set the scan time to 80000 still the same issue.

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @runecatz , V1.2.0 is released, update and try.
Please submit the log and your configuration of the last control failure.
By the way, restart HomeBridge after updating the config file.

**Comment by bx67212** [comment]
Same here...

P.s  is possible to have openhab plugin?

**Comment by virtualxdriver** [comment]
Could it be that this project only supports Raspberry Pi and not Mac computers? I could not get it to discover my accessories from my Mac mini either, although zizi4n5/homebridge-switchbot-for-mac works perfectly.

**Comment by runecatz** [comment]
I too am using a Mac, are their any homebridge plugin which supports Mac and SwitchBot Curtain. Just want to integrate SwitchBot curtain into my morning HomeKit automation. Proofing more difficult than expected!

I would have used IFTTT plugin which is what I’ve done before but now IFTTT charge to create new applets, I don’t really want to pay a subscription just to do this simple thing.

**Comment by bx67212** [comment]
@runecatz @virtualxdriver confirmed: noble dependence is very "strict"...

I flash again my raspberry sd to convert all my openhab things to homebridge and... Im very happy 👯‍♂️ 

All works done! Alexa too 🥇

**Comment by DJay-X** [comment]
> I too am using a Mac, are their any homebridge plugin which supports Mac and SwitchBot Curtain. Just want to integrate SwitchBot curtain into my morning HomeKit automation. Proofing more difficult than expected! 

This is why I deeply hope for a non-bluetooth solution using Hub and API. https://github.com/SwitchBot/homebridge-switchbot-ble/issues/1

**Comment by SwitchBot-Wonderlabs** [comment]
@runecatz We will release the RESTful API of Hub as soon as possible.

**Comment by runecatz** [comment]
Brilliant I look forward to it :)

**Comment by samsonrosen** [comment]
Hi @SwitchBot-Wonderlabs whilst the API will be great there are other plugins that use bluetooth noble and switchbot that support Mac OS. It would be great if this BLE plugin could be updated to be Mac compatible too. I’m happy to test. As noted in my issue switchbot for Mac works.

https://github.com/zizi4n5/homebridge-switchbot-for-mac

**Comment by dnicolson** [comment]
There seems to be a problem with [noble](https://github.com/abandonware/noble) on macOS at the moment, addresses are being returned as empty strings. Less than a year ago MAC addresses were returned correctly with the `discover` event.

The following code displays addresses on a Raspberry Pi but not on macOS:
```
const noble = require('@abandonware/noble');

const uuidPrimary = 'cba20d00224d11e69fb80002a5d5c51b';
const uuidWrite = 'cba20002224d11e69fb80002a5d5c51b';

noble.on('stateChange', state => {
  if (state === 'poweredOn') {
    noble.startScanning([uuidPrimary], false);
  } else {
    noble.stopScanning();
  }
});

noble.on('discover', peripheral => {
  console.log(`ID: ${peripheral.id}\nAddress: ${peripheral.address}\n`);
});
```

**Comment by dnicolson** [comment]
There are two reasons why this occurs on macOS:
1. The core Bluetooth LE package [noble](https://github.com/abandonware/noble) requires that a connection be made at least once, this does not happen so the MAC address will always be empty. This affects the bot and the curtain.
2. The underlying SwitchBot package [node-switchbot](https://github.com/futomi/node-switchbot) only supports Linux, https://github.com/futomi/node-switchbot/pull/14 adds Mac support though. This affects the meter.

**Comment by SwitchBot-Wonderlabs** [comment]
https://github.com/futomi/node-switchbot/pull/17
