### ISSUE TITLE
SwitchBot meter doesn't show temperature below zero  

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-ble#36]
**Describe The Bug:**

SwitchBot meter temperature shows 0 once it detects a temperature below 0.
**To Reproduce:**

**Expected behavior:**

**Logs:**
[2020-12-25, 9:55:36 p.m.] [SwitchBotPlatform] Bonus Room current temperature: -3.3℃
[2020-12-25, 9:55:36 p.m.] [SwitchBotPlatform] Bonus Room current humidity: 72%

**Homebridge Config:**
            {
                    "type": "meter",
                    "name": "Bonus Room",
                    "bleMac": "xx:64:35:4A:A3:xx",
                    "scanDuration": 2000,
                    "scanInterval": 60000
                }

**Screenshots:**
![image](https://user-images.githubusercontent.com/48269361/103145825-a0993f00-46fd-11eb-940a-c3d956cb8e68.png)

**Device Model: Raspberry pi 3 b+**

# **Environment:**

- **Node.js Version: v14.15.3**: 
- **NPM Version: v6.14.9**: 
- **Homebridge Version: v1.2.3**: 
- **Homebridge SwitchBot BLE Plugin Version: v1.2.7**:
- **Homebridge Config UI X Plugin Version: v4.36.0**:
- **Operating System: Raspbian GNU/Linux Stretch (9)**:

**Comment by SwitchBot-Wonderlabs** [comment]
Hi, @jonpeng , that is not a bug.
The minimum value of the chaharacteristic "Current Temperature" is 0 in HomeKit Accessory Protocol Specification R15.

**Comment by jonpeng** [comment]
Thank you!
