### ISSUE TITLE
Curtain status

### ISSUE THREAD

**Issue by jonpeng** [OpenWonderLabs/homebridge-switchbot-ble#37]
The curtain status won't be updated in HomeKit if the curtain was operated by another APP(such as SwitchBot app, Alexa, etc) or by manually (touch n go).

**Comment by Damianeq90** [comment]
Hello,
I have the same problem, if the curtain has changed its position manually (Touch and Go) or in an application other than Home, the status of the curtain is not updated.

**Comment by dnicolson** [comment]
This is a duplicate of https://github.com/OpenWonderLabs/homebridge-switchbot-ble/issues/14.
