### ISSUE TITLE
Access to IR Functions

### ISSUE THREAD

**Issue by jonzhan** [OpenWonderLabs/homebridge-switchbot-ble#57]
**Is your feature request related to a problem? Please describe.**

It would be very useful to be able to send commands to configured IR devices via the Switchbot Hub. 

**Describe the solution you'd like**

Ideally it would be possible to interact with devices configured in the app, but even manual entry of hex codes in the homebridge config file would be very useful!

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by SwitchBot-Wonderlabs** [comment]
Hey, @jonzhan , there has no such interface via BLE,
try [homebridge-switchbot-openapi](https://github.com/OpenWonderLabs/homebridge-switchbot-openapi).
