### ISSUE TITLE
Switchbot does not press

### ISSUE THREAD

**Issue by ivanmaj** [OpenWonderLabs/homebridge-switchbot-ble#8]
Hey switchbot community,

just installed the plugin on my homebridge. Let me explain my use case: I am using a switchbot as a door opener. 

When using the app there is no problem. Also, when i try to discover the switchbot with the raspberry pi bluetooth tool I always get a response and the raspberry pi can find the switchbot with the given BLE address. 

Pressing the button in the Home-App and if i look in the homebridge logs, I only get:
[SwitchbotPlatform] Current state of the switch was returned: OFF

That's all i get and the switchbot does nothing. I only need that the switchbot does a "press" when I turn it on in the Home-app and reset to the  non-pressed mode after about 3 seconds. 

Maybe someone else got a solution? Why does the "press-mode" can not be triggered?

**Comment by SwitchBot-Wonderlabs** [comment]
#2 
The plug-in supports Press mode.
You can set the press-hold time in the advanced settings of the app.
```
[SwitchBotPlatform] Scan done.
[SwitchBotPlatform] WoHand (d4:cc:43:97:ae:2c) was found.
[SwitchBotPlatform] Pressing the switch...
[SwitchBotPlatform] Done.
[SwitchBotPlatform] Switch state has been set to: OFF
[SwitchBotPlatform] Current state of the switch was returned: OFF
```

**Comment by ivanmaj** [comment]
Hello switchbot Team, 

thanks for the fast answer. Just checked my homebridge and got this information:
[2020-11-10 13:20:09] [SwitchBotPlatform] Initializing SwitchBotPlatform platform...
[2020-11-10 13:20:09] [SwitchBotPlatform] Example platform finished initializing!
[2020-11-10 13:20:09] [SwitchBotPlatform] Example switch 'Frontdoor' created!
[2020-11-10 13:20:09] [SwitchBotPlatform] Device amount: 1
[2020-11-10 13:20:09] Initializing platform accessory 'Frontdoor'...
[2020-11-10 13:22:48] [SwitchBotPlatform] Current state of the switch was returned: OFF
noble warning: adapter state unauthorized, please run as root or with sudo
               or see README for information on running without root/sudo:
               https://github.com/sandeepmistry/noble#running-on-linux

Seams like there is something wrong with my noble plugin?

**Comment by CooperCGN** [comment]
Maybe increase the scan duration in your config.
